# examples/__init__.py

from examples.decision_tree import decision_tree_example
from examples.k_means import k_means_example
from examples.k_nearest_neighbors import k_nearest_neighbors_example
from examples.linear_regression import linear_regression_example
from examples.logistic_regression import logistic_regression_binary_example, logistic_regression_multiclass_example
from examples.naive_bayes import naive_bayes_example
from examples.random_forest import random_forest_example
from examples.support_vector_machines import support_vector_machines_binary_example
